server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mythread?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  application:
    name: 订单服务

